import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import type { AppProps } from 'next/app';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/context/themeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          <main className='max-w-2xl mx-auto py-10'>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
